routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('cars','CarController');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $fillable = ['plate', 'year', 'brand', 'model'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use Illuminate\Http\Request;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $cars = Car::latest()->paginate(5);
      
      return view('cars.index',compact('cars'))
      ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'plate' => 'required',
        'year' => 'required',
        'brand' => 'required',
        'model' => 'required',
      ]);
      
      Car::create($request->all());
      
      return redirect()->route('cars.index')
        ->with('success','Auto creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
      return view('cars.show',compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
      return view('cars.edit',compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
      $request->validate([
        'plate' => 'required',
        'year' => 'required',
        'brand' => 'required',
        'model' => 'required',
      ]);

      $car->update($request->all());
      
      return redirect()->route('cars.index')
        ->with('success','Auto actualizado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
      $car->delete();
      
      return redirect()->route('cars.index')
        ->with('success','Auto eliminado exitosamente.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cars/create.blade.php
@extends('cars.layout')

@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Agrega un nuevo Auto</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{ route('cars.index') }}"> Back</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> There were some problems with your input.<br><br>
  <ul>
  @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
  @endforeach
  </ul>
</div>
@endif

<form action="{{ route('cars.store') }}" method="POST">
  @csrf
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Patente: </strong>
        <input type="text" name="plate" class="form-control" placeholder="ingresa una patente ex: PK-MN-80">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Marca: </strong>
        <input type="text" name="brand" class="form-control" placeholder="ingresa una marca ex: Audi">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Modelo: </strong>
        <input type="text" name="model" class="form-control" placeholder="ingresa un modelo ex: R5">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Año: </strong>
        <input type="number" name="year" class="form-control" placeholder="ingresa el año de tu auto">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>
@endsection

resources/views/cars/edit.blade.php
@extends('cars.layout')

@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Modificar Auto</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{ route('cars.index') }}"> Back</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> There were some problems with your input.<br><br>
  <ul>
  @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
  @endforeach
  </ul>
</div>
@endif

<form action="{{ route('cars.update', $car->id) }}" method="POST">
  @csrf
  @method('PUT')
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 d-none">
      <div class="form-group">
        <strong>ID: </strong>
        <input type="text" name="plate" value="{{ $car->id }}" class="form-control" disabled>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Patente: </strong>
        <input type="text" name="plate" value="{{ $car->plate }}" class="form-control" placeholder="ingresa una patente ex: PK-MN-80">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Marca: </strong>
        <input type="text" name="brand" value="{{ $car->brand }}" class="form-control" placeholder="ingresa una marca ex: Audi">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Modelo: </strong>
        <input type="text" name="model" value="{{ $car->model }}" class="form-control" placeholder="ingresa un modelo ex: R5">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Año: </strong>
        <input type="number" name="year" value="{{ $car->year }}" class="form-control" placeholder="ingresa el año de tu auto">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>
@endsection

resources/views/cars/index.blade.php
@extends('cars.layout')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Laravel 7 CRUD - Autos</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-success" href="{{ route('cars.create') }}"> Create New Product</a>
      </div>
    </div>
  </div>

  @if ($message = Session::get('success'))
      <div class="alert alert-success">
          <p>{{ $message }}</p>
      </div>
  @endif

  <table class="table table-bordered">
    <tr>
      <th>Patente</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Año</th>
      <th width="280px">acciones</th>
    </tr>
    @foreach ($cars as $car)
    <tr>
      <td>{{ $car->plate }}</td>
      <td>{{ $car->brand }}</td>
      <td>{{ $car->model }}</td>
      <td>{{ $car->year }}</td>
      <td>
        <form action="{{ route('cars.destroy',$car->id) }}" method="POST">
          <a class="btn btn-info" href="{{ route('cars.show',$car->id) }}">Show</a>
          <a class="btn btn-primary" href="{{ route('cars.edit',$car->id) }}">Edit</a>
          @csrf
          @method('DELETE')
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </td>
    </tr>
    @endforeach
  </table>
  {!! $cars->links() !!}
@endsection

resources/views/cars/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>Laravel 7 CRUD Ejemplo</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    @yield('content')
  </div>
</body>
</html>

resources/views/cars/show.blade.php
@extends('cars.layout')

@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Detalles de Auto</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{ route('cars.index') }}">Back</a>
    </div>
  </div>
</div> 

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 d-none">
    <div class="form-group">
      <strong>ID: </strong>
      {{ $car->id }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Patente: </strong>
      {{ $car->plate }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Marca: </strong>
      {{ $car->brand }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Modelo: </strong>
      {{ $car->model }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Año: </strong>
      {{ $car->year }}
    </div>
  </div>
</div>
@endsection